litmuschaos/pages

- README.md
- Fix markdown syntax on README.md 
Signed-off-by: ksatchit <karthik.s@openebs.io>
> (refactor)readme:improve readme formatting

- index.yaml
Signed-off-by: ksatchit <karthik.s@openebs.io>
> (refactor)index.yaml: remove redundant chart details

- charts/litmusInfra/templates/chaosengine_crd.yaml
- charts/litmusInfra/templates/deployment.yaml
- charts/litmusInfra/values.yaml
- Chaos Operator is integrated into LitmusInfra
Signed-off-by: ksatchit <karthik.s@openebs.io>
> merge litmusInfra and operator charts

- charts/k8sChaos/values.yaml
Signed-off-by: ksatchit <karthik.s@openebs.io>
> add default ansible stdout callback

- docs/litmus-operator-v0.7.0.yaml
Signed-off-by: Raj <mail.rajdas@gmail.com>
> adding litmus operator spec for 0.7

- docs/litmus-operator-v0.7.0.yaml
Signed-off-by: Raj <mail.rajdas@gmail.com>
> removing docker image tag from 0.7 to 0.7.0

- docs/litmus-operator-ci.yaml
- Ensure that the correct tag is present for operator image based on master
> (refactor)update image tag on latest operator yaml

- docs/litmus-operator-v0.8.0.yaml
Signed-off-by: chandan kumar <chandan.kr404@gmail.com>
> (Release): Add chaos-operator yaml for v.8.0

- docs/litmus-operator-v1.0.0-RC1.yaml
- Add new operator for 1.0.0-RC1 
- Introduce newer CRDs with schema validation
> (feat) add operator yaml for 1.0.0-RC1

- docs/litmus-operator-v1.0.0.yaml
- Add the 1.0.0 litmus operator yaml 
> (refactor) update 1.0.0 operator yaml

- docs/litmus-operator-v1.1.0.yaml
- Add v1.1.0 operator into pages 
> (feat) add v1.1.0 litmus operator

- charts/litmus/templates/chaosresult_crd.yaml
- docs/litmus-operator-ci.yaml
Signed-off-by: shubhamchaudhary <shubham.chaudhary@mayadata.io>
- Remove status subresource from the chaos-result
> refactor(chaos-result): Remove status subresource from the chaos-result

- docs/litmus-operator-v1.2.0.yaml
- Adds manifests for v1.2.0 LitmusChaos operator 
> (chore)release: add operator manifest for 1.2.0 release

- charts/README.md
- docs/litmus-admin-rbac.yaml
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
> (feat) Added litmus-admin-rbac, superset of all experiments

- docs/litmus-operator-latest.yaml
- docs/litmus-operator-v1.3.0-RC1.yaml
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
> (chore) Create v1.3-RC1 tag litmus-operator

- docs/litmus-admin-rbac.yaml
Signed-off-by: ksatchit <karthik.s@mayadata.io>
> (fix)rbac: remove redundant resources

- docs/litmus-operator-v1.4.0.yaml
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
> (fix) Latest v1.4.0 Operator image tag fix

- docs/litmus-operator-v1.4.0.yaml
Signed-off-by: ksatchit <karthik.s@mayadata.io>
> (chore)operator: update operator image to 1.4.1

- docs/litmus-operator-v1.5.0.yaml
Signed-off-by: Raj Das <mail.rajdas@gmail.com>
adding litmus 1.5 operator yaml
> chore(charts): Litmus 1.5 operator yaml

- docs/litmus-operator-v1.6.0-RC1.yaml
Signed-off-by: shubhamchaudhary <shubham.chaudhary@mayadata.io>
> chore(charts): Litmus 1.6.0-RC1 operator yaml

- docs/litmus-operator-v1.6.0.yaml
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
> feat(1.6.0): Add litmus-operator for 1.6.0

- docs/litmus-operator-ci.yaml
- docs/litmus-operator-latest.yaml
- docs/litmus-operator-namespaced-scope.yaml
- docs/litmus-operator-v1.6.1.yaml
Signed-off-by: shubhamchaudhary <shubham.chaudhary@mayadata.io>
> feat(1.6.1): Adding the openapi validations and Adding 1.6.1 image
